export const PRODUCT_FILTERS = Object.freeze([
  { id: "all", label: "All" },
  { id: "everyday", label: "Everyday Banking" },
  { id: "savings", label: "Savings & Investments" },
  { id: "credit", label: "Credit Cards" },
  { id: "loan", label: "Loans" },
  { id: "insurance", label: "Insurance" },
]);

export const PRODUCT_CATALOG = Object.freeze([
  {
    id: "current",
    name: "Main Account",
    category: "Everyday Banking",
    filterCategory: "everyday",
    productKind: "account",
    accountType: "current",
    description: "Daily banking, cards, and payments.",
    monthlyFee: 50,
    currency: "ZAR",
    benefits: ["Cards", "Bill payments", "Transfers"],
    status: "available_now",
  },
  {
    id: "student",
    name: "Student Account",
    category: "Everyday Banking",
    filterCategory: "everyday",
    productKind: "account",
    accountType: "student",
    description: "Low-fee banking built for students and first-time earners.",
    monthlyFee: 0,
    currency: "ZAR",
    benefits: ["Cards", "Bill payments", "Low fees"],
    status: "available_now",
  },
  {
    id: "private_banking",
    name: "Private Banking",
    category: "Everyday Banking",
    filterCategory: "everyday",
    productKind: "account",
    accountType: "private_banking",
    description: "Premium everyday banking with priority support and flexible banking service.",
    monthlyFee: 150,
    currency: "ZAR",
    benefits: ["Priority support", "Flexible banking", "Cards"],
    status: "available_now",
  },
  {
    id: "savings",
    name: "TruSave",
    category: "Savings & Investments",
    filterCategory: "savings",
    productKind: "account",
    accountType: "savings",
    description: "A simple savings account for building healthy money habits.",
    monthlyFee: 0,
    currency: "ZAR",
    benefits: ["No monthly fee", "Transfers", "Flexible saving"],
    status: "available_now",
  },
  {
    id: "fixed_deposit",
    name: "Fixed Deposit",
    category: "Savings & Investments",
    filterCategory: "savings",
    productKind: "account",
    accountType: "fixed_deposit",
    description: "Lock funds away and earn more on money you will not need immediately.",
    monthlyFee: 0,
    currency: "ZAR",
    benefits: ["Long-term saving", "Disciplined growth", "Investment option"],
    status: "available_now",
  },
  {
    id: "tax_free_savings",
    name: "Tax-Free Savings",
    category: "Savings & Investments",
    filterCategory: "savings",
    productKind: "account",
    accountType: "tax_free_savings",
    description: "Grow long-term savings in a tax-efficient wrapper.",
    monthlyFee: 0,
    currency: "ZAR",
    benefits: ["Tax-free growth", "Long-term saving", "No card needed"],
    status: "available_now",
  },
  {
    id: "credit_card",
    name: "NexBank Credit Card",
    category: "Credit Cards",
    filterCategory: "credit",
    productKind: "credit",
    description: "Flexible credit for everyday purchases and online spending.",
    monthlyFee: 40,
    currency: "ZAR",
    benefits: ["Credit line", "Online payments", "Digital servicing"],
    status: "apply_later",
  },
  {
    id: "personal_loan",
    name: "Personal Loan",
    category: "Loans",
    filterCategory: "loan",
    productKind: "loan",
    description: "Structured borrowing for planned expenses and milestones.",
    monthlyFee: 0,
    currency: "ZAR",
    benefits: ["Fixed repayments", "Simple application", "Flexible terms"],
    status: "coming_soon",
  },
  {
    id: "insurance",
    name: "NexBank Insurance",
    category: "Insurance",
    filterCategory: "insurance",
    productKind: "insurance",
    description: "Protect your lifestyle with future cover options from NexBank.",
    monthlyFee: 0,
    currency: "ZAR",
    benefits: ["Future cover", "Flexible options", "Digital support"],
    status: "apply_later",
  },
]);
